name: CI/CD Pipeline for PDF microservice deployment on GCR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker --quiet

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/${{secrets.PDF_CONTAINER_REGISTRY}}:${{ github.sha }} -f Dockerfile .
        working-directory: apps/pdf-service-backend

      - name: Push Docker Image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{secrets.PDF_CONTAINER_REGISTRY}}:${{ github.sha }}
        working-directory: apps/pdf-service-backend

      - name: Deploy to Cloud Run
        env:
          PDF_GCR_ENV: ${{ secrets.PDF_GCR_ENV }}
        run: |
          ENV_VARS=$(echo "${PDF_GCR_ENV}" | tr '\n' ',' | sed 's/,$//')
          gcloud run deploy ${{ secrets.PDF_CLOUD_RUN_SERVICE }} \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/${{secrets.PDF_CONTAINER_REGISTRY}}:${{ github.sha }} \
            --platform managed \
            --region asia-southeast1 \
            --set-env-vars $ENV_VARS \
            --verbosity=debug
